services:
  bot:
    build: .
    depends_on:
      database:
        condition: service_healthy
    links: 
      - database
  database:
    image: postgres:latest
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "picciottocanudobot"]
      interval: 5s
      timeout: 10s
      retries: 5