#bad stuffs here, cover your eyes with prosciutto if you don't wanna become blind ,,
STRINGS = {
    "start": "Ciao, questo bot ti aiuterà a vendere i tuoi libri usati creando annunci da mandare in <a href='https://t.me/+hyLW-12n5To3OWU0'>Canudo Libri</a>, un canale dedicato a ciò e promosso per passa parola nell'istituto.\n\nBot sviluppato utilizzando <a href='https://python.org'>Python</a> e <a href='https://docs.pyrogram.org'>Pyrogram</a>.",
    "write_ad_btn": "Vendi un libro",
    "source_code_btn": "Codice sorgente",
    "ad_subject_selection": "Seleziona una materia tra quelle elencate, se ne manca qualcuna segnalalo: @branchscope :)",
    "ad_bookname_imposteiscion": "Scrivi il nome del libro che vuoi vendere.",
    "ad_bookcode_imposteiscion": "Scrivi il codice del libro che vuoi vendere. (facoltativo)",
    "ad_years_selection": "Seleziona gli anni per cui questo libro è valido (puoi selezionarne più di uno grazie alla scienza delle matriosche):",
    "ad_contacts_imposteiscion": "Ora scrivi qui sotto i social networks dove la gente potrà contattarti per il libro.\n\nAO miraccomando a scriverli così:\nInstagram - instagram.com/branchscope\nNumero - +393214567890",
    "ad_contacts_imposteiscion_error": "AO, CHE T'HO DETTO? DEVI SCRIVERLI COSÌ:\nInstagram - instagram.com/branchscope\nNumero - +393214567890\n\nNon per romperti le scatole, ma sto bot è automatico e il mio sviluppatore m'ha detto di fare così...",
    "done": "Fatto",
    "done_send": "Fatto, inviamo nel canale o scancelli tutto?",
    "skip_set_bookcode_btn": "Salta passaggio",
    "send_ad_btn": "Spedisci annuncio",
    "cancel_ad_btn": "Cancella annuncio",
    "url_btn": "Link annuncio",
    "congrats": "Fatto, puoi trovare e gestire il tuo annuncio cliccando sul bottone qua sotto (ti fisso anche il messaggio così lo trovi subito):",
    "ad": "<b>NUOVO ANNUNCIO!</b>\n\n<b>Nome del libro:</b> {BOOK_NAME}\n{BOOK_CODE_STR}<b>Materia:</b> {SUBJECT}\n<b>Anno/i:</b> {YEARS}\n<b>Contatti:</b> {CONTACTS}\n\nPubblicato da <a href='tg://user?id={FROM_USER_ID}'>{FROM_USER_NAME}</a>"
}
